### ISSUE TITLE
Unable to set profiles for container

### ISSUE THREAD

**Issue by dgengtek** [NexusSW/kitchen-lxd_sling#10]
I am not able to set any profiles to my containers. Only default profile is used. Any clue?
```

driver:
  name: lxd
  username: kitchen
  profiles:
    - docker
```

test-kitchen (1.21.2)
kitchen-lxd_sling (0.5.5)
